name: Dota Challenge Checker
permissions:
  contents: write
on:
  schedule:
    - cron: '0,30 * * * *'

  workflow_dispatch: # allows manual run

jobs:
  run_checker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo (needed to access code and store.json)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the checker
      - name: Run Dota Challenge Checker
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python main.py

      # Commit updated store.json if changed
      - name: Commit store.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add store.json
          git add smooo_king_bot_leaderboard.txt
          git diff --cached --quiet || git commit -m "Update store.json"
          git push
